version: "3"
services:
    mongoDBContainer:
        image: mongo:latest
        container_name: "mongoDBContainer"
        ports:
            - 27017:27017
    userservice-mongo:
        image: amizazad/userservice:v1.1
        container_name: "userservice-mongo"
        ports:
            - 8080:8080
        links:
            - mongoDBContainer